name: "Compiler App Flipper"
on: 
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Récupérer le code
      uses: actions/checkout@v4
      
    - name: Compiler avec ufbt
      uses: flipperdevices/flipperzero-ufbt-action@v0.1.2
      with:
        task: build

    - name: Sauvegarder le fichier .fap
      uses: actions/upload-artifact@v4
      with:
        name: mon_app_flipper
        path: dist/*.fap
